version: '3.7'
services:
  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:java -jar db-api.jar
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
